name: macOS Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'

    - name: Resolve Dependencies
      run: |
        cd ProtonDrive-macOS
        xcodebuild -resolvePackageDependencies \
          -scheme "ProtonDrive-macOS-Store" \
          -derivedDataPath ../DerivedData

    - name: Build App
      run: |
        cd ProtonDrive-macOS
        xcodebuild -project ProtonDrive-macOS.xcodeproj \
                  -scheme "ProtonDrive-macOS-Store" \
                  -configuration Release \
                  -derivedDataPath ../DerivedData \
                  CODE_SIGN_IDENTITY="-" \
                  CODE_SIGNING_REQUIRED=NO \
                  SYMROOT="$(pwd)/../build"

    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "Proton Drive" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "ProtonDrive.app" 200 190 \
          --hide-extension "ProtonDrive.app" \
          --app-drop-link 600 185 \
          "ProtonDrive.dmg" \
          "build/Release/ProtonDrive.app"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ProtonDrive-${{ github.sha }}
        path: ProtonDrive.dmg